name: chs_crm
description: "A CRM system for foreclosure and real estate file management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Updated to latest compatible versions
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  file_picker: ^8.1.2

  # HTML parsing for web scraping
  html: ^0.15.4      
  
  # State Management
  provider: ^6.1.2

  # Theme Storage
  shared_preferences: ^2.3.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Utilities
  intl: ^0.19.0
  web: ^1.1.1
  http: ^1.1.0
  flutter_html: ^3.0.0
  csv: ^6.0.0
  flutter_pdf_text: ^0.9.0
  string_scanner: ^1.4.1
  pdf: ^3.11.3
  printing: ^5.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Only include fonts that actually exist in your assets/fonts folder
  fonts:
  - family: PassionOne
    fonts:
      - asset: assets/fonts/PassionOne-Regular.ttf
      - asset: assets/fonts/PassionOne-Black.ttf
      - asset: assets/fonts/PassionOne-Bold.ttf

  - family: SFPro
    fonts:
      - asset: assets/fonts/BlackItalic.otf
      - asset: assets/fonts/DisplayBold.otf  
      - asset: assets/fonts/HeavyItalic.otf 
      - asset: assets/fonts/LightItalic.otf 
      - asset: assets/fonts/Medium.otf 
      - asset: assets/fonts/Regular.otf 
      - asset: assets/fonts/SemiBold.otf 
      - asset: assets/fonts/ThinItalic.otf      
      - asset: assets/fonts/UltraLightItalic.otf